{% set name = "bash_kernel" %}
{% set version = "0.7.2" %}
{% set sha256 = "a08c84eddd8179de5234105821fd5cc210015671a0bd3cd0bc4f631c475e1670" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 3
  script: python -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - ipykernel
    - pexpect >=4.0
    - pip <19.0  # Fix issue with pep517 BackendUnavailable
    - python
  run:
    - ipykernel
    - pexpect >=4.0
    - python

test:
  imports:
    - bash_kernel
  commands:
    - jupyter kernelspec list | grep bash

about:
  home: "https://github.com/takluyver/bash_kernel"
  license: "BSD"
  license_family: "BSD"
  license_file: "LICENSE"
  summary: "A bash kernel for Jupyter"

extra:
  recipe-maintainers:
    - conda-forge/python
    - PertuyF
